feat: adjust code according to scripts restructure
readyplayerme/Unity-WebView pull request #10
Opened 2022-12-08 13:34 UTC by rYuuk

## [TICKETID](https://ready-player-me.monday.com/boards/2563815861/pulses/TICKETID)

## Description

-   Briefly describe what this change will do

## Changes

#### Added

-   List your additions and new features here.

#### Updated

-   List your updates and changes here.

#### Removed

-   List what is removed here.

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

## QA Testing

-   Mention any useful test cases for this feature and add to QA Testing documentation.

## Details

-   If more details are necessary to support the description with images and videos add them here.

2022-12-12 11:03 UTC, HarrisonHough requested changes
small naming to fix (Subdomain)

2022-12-12 11:03 UTC, HarrisonHough commented on Runtime/WebViewPanel.cs
> +            var partnerSubdomain = CoreSettings.PartnerSubDomainSettings.Subdomain;
Just need to update SubDomain to subdomain
```suggestion
            var partnerSubdomain = CoreSettings.PartnerSubdomainSettings.Subdomain;
```

2022-12-13 07:50 UTC, HarrisonHough approved these changes
looks good now. 
Just FYI, probably best to only merge once the other PR's are also approved so you can merge them all together to prevent issues.

2022-12-13 10:29 UTC, srcnalt approved these changes

2022-12-13 12:37 UTC, merged